### ISSUE TITLE
Dev config not playing nice with storage of assets

### ISSUE THREAD

**Issue by technomage** [Magical-Threads/8th-mind#11]
Configuration change made to use local server when working in development mode. This looks for http://localhost:3000/storage ... for assets, which do not appear to be found there. Please advise on where images are stored, and I will adjust configs to properly locate them. I could change images back to api.8thmind.com but then any local work would not be matched to the external assets.

**Comment by marioluevanos** [comment]
I think that was never set up for locally stored assets. If you know how to set that up, please do so, otherwise might have to change it back.

**Comment by technomage** [comment]
It looks like the config is ok.  The issue is that the /storage directory was not updated when the database dump was created.  Please create a new database dump and clone the storage directory from the server at the same time.

**Comment by technomage** [comment]
Both dev and production use docker and the storage dir is mapped to the local directory structure.  In test a different config is required.  Configs set up for dev/test/prod.
