### ISSUE TITLE
Workflow change input needed

### ISSUE THREAD

**Issue by technomage** [Magical-Threads/8th-mind#16]
The workflow for creating a submission has been modified to comply with the upload component I found that supports s3 (next phase).  I need input on whether this is acceptable.  In the new workflow you enter the title and caption and when you select the file it is uploaded and the submission and asset created.  If you need a "create" button it will take more work to get the component to save the files and use them when the button is pressed.

**Comment by marioluevanos** [comment]
The new modification sounds good. It sounds like it saves a step.

So, is the action taken on input events, instead of button click?

**Comment by technomage** [comment]
The user fills in the text fields, then clicks the file selection button.  The upload and submission create happens when the user selects a file for upload.
