### ISSUE TITLE
Add User Profiles

### ISSUE THREAD

**Issue by marioluevanos** [Magical-Threads/8th-Mind#18]
Currently there are users, but there is no user profiles.

The user profiles should contain:

- First Name
- Last Name
- Avatar
- Bio
- URL
- Location

I will provide a UI mockup/specs for the profile page. (still waiting on UI designs.)

Can we plan the backend for user profiles?

**Comment by technomage** [comment]
This just looks like a few more fields on user.  Any reason to have a separate profile record in database?

**Comment by blazhilar** [comment]
I believe this can be achieved by simply adding the fields onto the existing user if possible there is no reason for duplicates. Is that what you intended?

**Comment by technomage** [comment]
Rough profile page added to UI and database schema updated in production to add url, bio, avatar, and location fields. Script is in server/schema.  Profile page accessed by clicking on user name in header after login.  Styling needed.
