### ISSUE TITLE
Gallery submissions should be able to delete

### ISSUE THREAD

**Issue by marioluevanos** [Magical-Threads/8th-mind#2]
Form needs to be able to delete the submission from the gallery. Please use this since it is the only article with submissions. http://localhost:4200/article/27/gallery

The submissions are located in:
* Route: `routes/article/gallery.js`
* Template: `templates/article/gallery.hbs`

And the 'challenge-submission' component is:
* `templates/components/challenge-submission.hbs`
* `components/challenge-submission.js`

Endpoints
* Delete submission 
`http://api.8thmind.com/articles/:articleID/submissions/:submissionID/`
* Delete submission asset
`http://api.8thmind.com/articles/:articleID/submissions/:submissionID/asset/:assetID`

**Comment by technomage** [comment]
Do you have security set up so that only the submitter or an admin can delete, or is that coming separately?

**Comment by marioluevanos** [comment]
I don't have a mechanism for that. 

The way I was adding a delete button, is to compare if the submission.userID matches the session.userID. I'm open to recommended changes.

**Comment by technomage** [comment]
The server wants either to have you delete the assets first, or add a force=true option to the delete.  Please advise which workflow you want.  Should the user delete the assets first then the submission, or can they delete the submission if it has assets?
