### ISSUE TITLE
Add a button to bottom on homepage to" read more" pointing to the header articles

### ISSUE THREAD

**Issue by Admiralmiles** [Magical-Threads/8th-mind#25]

**Comment by blazhilar** [comment]
For reference

![capture5](https://user-images.githubusercontent.com/31456787/33688486-660918ce-da90-11e7-9b64-1ab4975a69b7.PNG)
![capture6](https://user-images.githubusercontent.com/31456787/33688487-6623f4c8-da90-11e7-8c70-9542aa8e3f94.PNG)

**Comment by technomage** [comment]
Button created, but styling needs work.

**Comment by blazhilar** [comment]
No problem we can handle styling
