### ISSUE TITLE
Infinite Scroll (lazy load) on Article, Challenges, Create pages. No more pagination. 

### ISSUE THREAD

**Issue by blazhilar** [Magical-Threads/8th-mind#26]

**Comment by blazhilar** [comment]
![screen shot 2017-12-04 at 3 55 50 pm](https://user-images.githubusercontent.com/31456787/33582782-c4de9cb0-d90b-11e7-8446-289ac85c5d34.png)

Currently there is also an issue that when challenges is selected the page is assumed blank however one needs to click next page multiple times to find the article. This new task will solve this issue.

**Comment by blazhilar** [comment]
Issue about wrong pagination fixed by michael (technomage)

**Comment by technomage** [comment]
changes for infinite scroll have been committed
