### ISSUE TITLE
Publish Date on articles HAS TO WORK so that we can schedule releases of all content!

### ISSUE THREAD

**Issue by blazhilar** [Magical-Threads/8th-mind#33]
As of right now the process of publishing is hard on the editors because the date function to publish isn't working as intended. Because of this the editor needs to publish the article on the morning of, instead of just setting a day to auto publish. (We don't want the editors to publish an article on christmas morning).

**Comment by technomage** [comment]
The authoring function only stores a date not a date time for articleStartDate please advise what time on each date you want the articles visible.  I presume that prior to the start date the system should not return articles to the site for display.

**Comment by technomage** [comment]
Change made to hide all articles from paginated result (articles page, create page, etc) when articleStartDate is not in the past/present.

**Comment by blazhilar** [comment]
9am is the established time as of right now but in future we would like to have variable time.

**Comment by technomage** [comment]
variable time will require changes to the admin app.

**Comment by blazhilar** [comment]
Understood, if you can make it 9am as of right now go ahead.

**Comment by blazhilar** [comment]
Issue is still persisting, our editor made a new article for tomorrow and it still shows on homepage

**Comment by technomage** [comment]
Which article?

**Comment by blazhilar** [comment]
As of right now our editor checked this and turns out it works so i think it was fixed
