### ISSUE TITLE
Publishing articles is met with this error

### ISSUE THREAD

**Issue by blazhilar** [Magical-Threads/8th-mind#34]
![8th mind publishing problem](https://user-images.githubusercontent.com/31456787/33786084-931aaab6-dc1c-11e7-97f6-e5738afd021b.jpg)

**Comment by technomage** [comment]
This looks like the same issue that happened recently that the prior developer addressed.  Do we have any idea what was done to resolve it at that time?

**Comment by blazhilar** [comment]
Looking into it now

**Comment by technomage** [comment]
When updating to a new production storage directory the script fix_admin_priviledges.sh needs to be run.  The script had out of date docker container name, which has been fixed in the source tree.

**Comment by technomage** [comment]
fix permissions script applied to server.  Please retest.
