### ISSUE TITLE
The user flow is fine, just it doesn't allow the user to finish the transaction of submitting, consequently leaving the gallery empty

### ISSUE THREAD

**Issue by blazhilar** [Magical-Threads/8th-mind#36]
![bug](https://user-images.githubusercontent.com/31456787/34183511-072c3684-e4d0-11e7-90bb-d6f0027fae24.PNG)

**Comment by technomage** [comment]
The submission is sent when you select the file.  There is no "submit" button, you just fill in the text and select a file and it is submitted.

**Comment by blazhilar** [comment]
The screenshot was a result of selecting the file, there wasn't any other consequence after that

**Comment by technomage** [comment]
what browser were you using?

**Comment by blazhilar** [comment]
Chrome

**Comment by technomage** [comment]
PC or Mac?

**Comment by technomage** [comment]
It was failing when the user was not logged in.  It now prompts you to log in before allowing a submission.
