### ISSUE TITLE
double bug, When allow submissions is active, there is another '=' at the top of the page. Also the time for the contest is not apparent where it is established.

### ISSUE THREAD

**Issue by blazhilar** [Magical-Threads/8th-Mind#37]
![bug 2](https://user-images.githubusercontent.com/31456787/34183574-5324d3fc-e4d0-11e7-83bf-41c1d35452a0.PNG)

**Comment by technomage** [comment]
The database does not have start/stop times.  We can display 9am Pacific but that would be static text.

**Comment by blazhilar** [comment]
odd, ok that needs to be a data field.

**Comment by technomage** [comment]
The double bars are explicitly in the source as SVG for some reason.  If you want them removed that can be easily done, but they were in the original content as provided.

**Comment by blazhilar** [comment]
if that was the intended design thats fine to keep them but they just cant overlap with the title

**Comment by technomage** [comment]
There are actually 2 sets of vertical lines.  One in the heading itself (which overlaps the text) and the other that overlaps the bottom of the rectangle.  Please specific which you wish removed if any.

**Comment by blazhilar** [comment]
the one overlapping the letters is the problem
