### ISSUE TITLE
Create submission fails

### ISSUE THREAD

**Issue by technomage** [Magical-Threads/8th-mind#6]
In attempting to test delete I tried to create a new submission so I could delete it.  The create process failed because the template references action "create" for challenge-submit and the code has createSubmission as an action without any implementation.

**Comment by marioluevanos** [comment]
Yes that's correct. The "action" name is referenced incorrectly. 

Once the name is referenced correctly. Can you help with the implementation of submitting?  

I don't have any code submitting (i.e. in the Adapter).

Also the endpoint for submitting. http://api.8thmind.com/articles/27/submissions/new

**Comment by technomage** [comment]
Ember data prefers json payloads over form input, but the current server expects form input.  I have a revised version using json, please advise if that is acceptable.

**Comment by technomage** [comment]
Logic refactored and working for now
