### ISSUE TITLE
It would be helpful if the readme file indicated how to access the docker based mysql from the host

### ISSUE THREAD

**Issue by technomage** [Magical-Threads/8th-mind#8]
It would be helpful to be able to access the mysql database directly from the dev host machine (localhost).  It would helpful if the access values needed to use a mysql client app were included in the readme.

**Comment by technomage** [comment]
Accessing mysql directly required adding a mapping for port 3306 to the docker-compose.yml file.  Advise if this should be committed to git.  Not sure how this might affect docker use in production.

**Comment by marioluevanos** [comment]
Sorry for the lack of documentation for that. But yes it's okay to commit the docker-compose file.

**Comment by technomage** [comment]
port open for now, have to decide if that is a good idea since prod does not currently use a different docker config.
